name: Run tests

on: [ push, pull_request ]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]
        python-version: [ "3.10" ]

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        shell: bash
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip list
          # Get antlr for build grammar parser
                    if [ "$RUNNER_OS" == "Linux" ]; then
                        sudo apt-get install antlr4
                    elif [ "$RUNNER_OS" == "Windows" ]; then
                        choco install antlr4
                    else
                        brew install antlr
                    fi

          #Create python parser files from grammar
          - name: Create grammar
            shell: bash
            run: |
              if [ "$RUNNER_OS" == "Linux" ]; then
                  cd project/parser
                  antlr4 -Dlanguage=Python3 grammarGQL.g4 -visitor -o dist
                  echo ""
                  echo "--- grammar directory after building ---"
                  ls
                  cd dist
                  echo ""
                  echo "--- generated files ---"
                  ls
                  cd ../../..
                  pwd
              elif [ "$RUNNER_OS" == "Windows" ]; then
                  cd project/parser
                  antlr4 -Dlanguage=Python3 grammarGQL.g4 -visitor -o dist
                  echo ""
                  echo "--- grammar directory after building ---"
                  ls
                  cd dist
                  echo ""
                  echo "--- generated files ---"
                  ls
                  cd ../../..
                  pwd
              else
                  cd project/parser
                  antlr -Dlanguage=Python3 grammarGQL.g4 -visitor -o dist
                  echo ""
                  echo "--- grammar directory after building ---"
                  ls
                  cd dist
                  echo ""
                  echo "--- generated files ---"
                  ls
                  cd ../../..
                  pwd
              fi

      - name: Test with pytest
        run: python ./scripts/run_tests.py
